### PR TITLE
Add Splitty Travel logo

### PR DESCRIPTION
**Pull request by nire0510**
A new ambitious online booking website which is built with Ember framework.

### CODE REVIEW

**Comment by wifelette** [comment]
No logo included. Please also change the description from a marketing message to a description of the use (a la "our front end site is built with Ember", or "our app is built using Ember".

Once that's sorted we should be good to merge :)

**Comment by nire0510** [comment]
Thanks!

Where should i put the images? Couldnt find any image folder which has the
other brands images in it.

**Comment by wifelette** [comment]
https://github.com/emberjs/website/tree/master/source/images/about

**Comment by nire0510** [comment]
Hi @wifelette, thank you for your help!
All set (Y)

**Comment by wifelette** [comment]
I can't pull it down to check right now, but just making sure you staged this, as the image doesn't _look like_ it's been resized (with white space) to the exact size of the box it's going in. That would make sure there isn't any unfortunate stretching.

Could just be my eyes though, just confirming.

**Comment by nire0510** [comment]
@wifelette great input, thanks. The width of the image was fine, I thought background is set to center of box w/o stretching it. Anyway - I resized both images to the right dimension.

**Pull request merged**
