### PR TITLE
Ember CLI docs project section

### PR DESCRIPTION
**Pull request by Mi6u3l**
## What it does
Ember CLI docs project section to Ember times

### CODE REVIEW

**Comment by Mi6u3l** [comment]
Unfortunately, I don't that info at the moment. I'm ok on closing the PR and have a more completed section when those questions are answered.

**Comment by Alonski** [comment]
No need to close it. See if you can get some extra info and if not we will merge this in tomorrow :)
Good luck @Mi6u3l !

**Comment by jenweber** [comment]
```

**Comment by jenweber** [comment]
Hey @Mi6u3l thanks so much for the kind words in your description! @ me on Slack if you have specific questions. This project is so new that it's not really quite ready for a flood of helpers - I was thinking of it as more of an opportunity to describe how work like this comes to be, rather than specifics of the project itself. See my comments in the ember-times Slack with more details.

For example, I might say something like:
"It might look like RFCs pop up overnight, but there's a lot of work and support that goes into them! For example, @jenweber is working on some new tutorials for ember-cli, specifically basic commands and how to make your first addon. The process began with brainstorming which parts of Ember needed docs writing the most..." then describe how I chatted with the cli-teams, got a couple early reviewers, etc. and please call those commenters out with a thank you! The call to action at the end should be to stay tuned for an RFC to land where people can comment, and later quest issues to contribute written content.

**Pull request closed without merging**
