### PR TITLE
List on 'Learn' page cuts in to side of page on mobile devices

### PR DESCRIPTION
**Pull request by Minimilk93**
I have followed the same styles that are present on the guides page to fix this. Added some padding to `ul` in articles within the `.learn` class so we do not worry about any headaches! 

As a result, the list on the learn page is now consistent and inline with the rest of the content. Screenshots included of before and after adding these changes :)

BEFORE
screen shot 2017-10-26 at 14 48 28

screen shot 2017-10-26 at 14 51 45

AFTER
screen shot 2017-10-26 at 14 48 53

screen shot 2017-10-26 at 14 51 39

Let me know if there are any issues! This project is fun to work on and love the new font! :)

### CODE REVIEW

**Comment by acorncom** [comment]
Looks like it works, thanks @Minimilk93 ! @MelSumner any thoughts on the CSS approach? Is this the way we want to do things long-term?

**Comment by Minimilk93** [comment]
@MelSumner sure no problem! Would you like screenshots?

**Comment by MelSumner** [comment]
@Minimilk93 yes please! Top level pages will be sufficient.

**Comment by locks** [comment]
There was some glitch with the review apps, I triggered a new deploy with is at https://ember-website-pr-3051.herokuapp.com. This way you don't need to run it locally to take the screenshots :)

**Pull request merged**
