### PR TITLE
Update MHElabs link due to it being 404.

### PR DESCRIPTION
**Pull request by jayphelps**
Updated this PR based on the discussion below.

~~Not sure if @mhelabs is still around and active? Maybe @vineet-sinha can chime in? Either way, it's currently a a dead link and being shown on the homepage.  ¯\_(ツ)_/¯~~

image

### CODE REVIEW

**Comment by rwjblue** [comment]
MHE Labs is no longer a thing :sob:.  I'll reach out to some of the MHE folks that I am working with to see if they have an alternate link.

**Comment by habdelra** [comment]
You can use this link: http://www.mheducation.com (and yeah that's Will and I on the front page :-)

**Comment by lukemelia** [comment]
Nice Ember Out East shirt!

**Comment by habdelra** [comment]
@lukemelia crazy how that worked out! I think will was wearing with wicked ember shirt too (must have been a meetup that day)

**Comment by vineet-sinha** [comment]
I agree with @habdelra - we should change it to a link to: http://www.mheducation.com

**Comment by jayphelps** [comment]
Updated PR to http://www.mheducation.com/, should be good to merge.

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
