### PR TITLE
add TPP to ember user list

### PR DESCRIPTION
**Pull request by leojh**

### CODE REVIEW

**Comment by kmiller915** [comment]
Email received. cc @wifelette

**Comment by wifelette** [comment]
Hi @leojh —please update the Yaml. Use, as in, how are you using Ember, not what does your product do ;) 

Also, can you confirm that your logo is the exact correct size? I'm not on a machine where I can pull it down and check right now.

**Comment by leojh** [comment]
Hi Leah. I meant to say that we are using ember to modernize our app but I will re write the use to be more clear. Also, the image should be the correct size and with a transparent background.

**Comment by leojh** [comment]
Let me know if this new use works for you :)

**Pull request merged**
