### PR TITLE
Added Audacious Inquiry to users

### PR DESCRIPTION
**Pull request by mrjavascript**
Added Audacious Inquiry to users

### CODE REVIEW

**Comment by wifelette** [comment]
@mrjavascript Please clarify how Ember is actually used at this company or in this product :)

**Comment by mrjavascript** [comment]
We do health care software and the application my team works on has a
really slick dashboard powered by Ember.  The code is ever so easy to
maintain because of it.  I can take a photo of my Tomster next to the AI
coffee cup I have tomorrow in the office if that works.

**Comment by wifelette** [comment]
Apologies, I meant in the PR, in the `use` field. It's supposed to be specific explanation, rather than marketing or just 'We <3 Ember' type stuff (even though happiness is awesome :p). We'll likely be adding categories at some point soon as will need this info to easily sort everyone. 

If you could replace the content there with "Using Ember in the dashboard of our health care software" or something, that'd be perfect. Needs a general rebase by now too—everything moves fast in EmberLand ;) Thanks!

**Comment by mrjavascript** [comment]
Rebased and made the suggested changes.  Thank you so much for your help.

--Mike

**Comment by wifelette** [comment]
Merged, thank *you* :)

**Comment by mrjavascript** [comment]
Thanks!

**Pull request merged**
