### PR TITLE
Add Khorus software to the list of ember users

### PR DESCRIPTION
**Pull request by chbonser**

### CODE REVIEW

**Comment by wifelette** [comment]
@chbonser The image _looks_ like it might be wider than specified in the Yaml file. Can you verify?

**Comment by chbonser** [comment]
@wifelette good catch. Image size has been adjusted.

**Comment by locks** [comment]
@chbonser thanks for the update, however, making the image be 210px wide instead of 420px means it will look blurry in "retina" displays. Do you want to resubmit before merging so it looks crisp for everyone?

**Comment by locks** [comment]
Thank you @chbonser :)

**Pull request merged**
