### PR TITLE
Add SoCal Tomster to tomsters page

### PR DESCRIPTION
**Pull request by pixelhandler**
The "Tom Star" Tomster is a local resident of SoCal, and an accomplished Hollywood director and actor.

### CODE REVIEW

**Comment by wifelette** [comment]
Hi @pixelhandler —

Do you know where this version came from? The new Tomsters all have the registered Trademark icon on them, which this had when it was licensed/commissioned, but it seems to have been removed :(

(We're also working on adding it to all the old ones, but I definitely don't want new ones floating out there that are incorrect or have been modified!)

cc @ryanponce

**Comment by ryanponce** [comment]
@wifelette James must have sent @pixelhandler the wrong file. I'll send him the correct one right now.

**Comment by wifelette** [comment]
Fab :) I'll wait for an update to the PR and merge!

**Comment by pixelhandler** [comment]
@wifelette @ryanponce I can change the image.

**Comment by pixelhandler** [comment]
@wifelette @ryanponce the correct image with ® is in this commit now. Thanks :)

**Comment by wifelette** [comment]
No no no, thank YOU! I usually have to do these myself, I've got a little backlog of Tomsters to add :stuck_out_tongue_winking_eye:

**Comment by pixelhandler** [comment]
@wifelette We really like the SoCal Tomster, thanks for everything! lemme know if you want help with adding more Tomsters to this file, I set aside Friday to work on Ember stuff.

**Pull request merged**
