### PR TITLE
Added Danish e-Infrastructure Cooperation to emberjs.com/ember-users/

### PR DESCRIPTION
**Pull request by ashokaditya**

### CODE REVIEW

**Comment by ashokaditya** [comment]
Thanks @sivakumar-kailasam for a prompt review :) I shall make the changes and update as soon as I can

**Comment by ashokaditya** [comment]
done 👍

**Comment by ashokaditya** [comment]
Thanks so much for a quick merge :)

**Comment by sivakumar-kailasam** [comment]
@ashokaditya 👍 Would be great to see a blog post on you/your team/org's experience with ember :)

**Comment by ashokaditya** [comment]
That would be great indeed. I'm the only one working with ember at DeIC so far. As soon as I'm finished cleaning up a few bugs I'd write one and make sure I share it with you.

**Pull request merged**
