### PR TITLE
Used release version from model to construct quick start guide.

### PR DESCRIPTION
**Pull request by welzie**
Link to quick start guide is no longer hard coded.

Fixes https://github.com/emberjs/website/issues/2628

### CODE REVIEW

**Comment by rwjblue** [comment]
👍

**Comment by rwjblue** [comment]
Would you mind making a PR to https://github.com/ember-learn/builds to fix this over there also?  In the long run, I think we want to remove this super old setup and use that ember-cli app instead.

**Comment by welzie** [comment]
@rwjblue, done https://github.com/ember-learn/builds/pull/9

**Comment by rwjblue** [comment]
Thank you!

**Comment by tomdale** [comment]
:+1:

**Comment by welzie** [comment]
@rwjblue this now links to a page that doesn't exist https://guides.emberjs.com/v2.6.1/getting-started/quick-start/.  Should this instead always reference the latest minor version (2.6.0 in this case)?

**Comment by locks** [comment]
@welzie confirm!

**Comment by welzie** [comment]
@locks @rwjblue Here is a fix for the broken link https://github.com/emberjs/website/pull/2635

**Pull request merged**
