### PR TITLE
add _colors.scss

### LINKED ISSUE #3146: Color Palette
Goal: Determine the correct color palette for the website

Considerations: 
- interactive elements should look interactive
- Must include:
-- Ember orange (E04E39)
-- White (#fdfdfd) & Black (#212121)
- must pass color contrast tests (use https://webaim.org/resources/contrastchecker/ or similar)

### PR DESCRIPTION
**Pull request by ctcpip**
resolves #3146

### CODE REVIEW

**Comment by ctcpip** [comment]
colors
colors-inv

**Comment by sivakumar-kailasam** [comment]
Had to close & reopen this because of a misconfiguration on Travis.

**Comment by amyrlam** [comment]
@ctcpip Talked about this with some folks on the Learning Team. Would you be cool with porting this over to https://github.com/ember-learn/ember-styleguide instead, and then we can see how it would work in repos consuming `ember-styleguide`? (We could trial color changes in the website when it is rewritten to be an Ember app.)

**Comment by ctcpip** [comment]
I can probably do that, but won't be able to get to it immediately.  Lots going on right now.  :)

**Comment by amyrlam** [comment]
Talked to ctpip on Discord. 

Noted plan to move to https://github.com/ember-learn/ember-styleguide instead on https://github.com/emberjs/website/issues/3146, closing this PR for now. Also emberification of https://github.com/emberjs/website is 🔜? 😄

**Pull request closed without merging**
