### PR TITLE
Add initializers guide

### PR DESCRIPTION
**Pull request by opsb**
This PR adds an Initializers section to the guides.

### CODE REVIEW

**Comment by locks** [comment]
Ping for status on this PR.

**Comment by stefanpenner** [comment]
@dgeb can you review this now that we have introduced the registry?

@locks thanks for the ping, we likely need to update since the recent container/registry split.

**Comment by locks** [comment]
This now needs to be PRed against emberjs/guides and rewritten for CLI, correct?

**Comment by trek** [comment]
Yes, this would need to target https://github.com/emberjs/guides now and be updated to reflect cli-style structure.

**Comment by trek** [comment]
We've migrated to a versioned guides project. Please reopen on https://github.com/emberjs/guides. Thanks!

**Pull request closed without merging**
