### PR TITLE
Minor CSS enhancements

### PR DESCRIPTION
**Pull request by zeppelin**
The original PR was made at the EmberConf Contributors Workshop. I've extracted these few commits (plus rebased onto master, of course), to be able to review & merge them in independently from other changes, such as the responsive stuff, etc.

### CODE REVIEW

**Comment by mixonic** [comment]
Sees good! @locks the build here looks to be failing because an ecryption key was missing or busted?

**Comment by locks** [comment]
Might be because it's a PR? At any rate I disabled builds for PRs,
hopefully once merge we won't have a problem.

**Comment by acorncom** [comment]
@locks Did you disable builds for PRs or deploys for PRs?  Looks like [this SO answer](http://stackoverflow.com/a/34055957/334913) might describe what we're after ...

**Comment by locks** [comment]
@acorncom I know, but I was being lazy :D

**Comment by mixonic** [comment]
@locks so should I merge this failing? What is the next step?

**Comment by mixonic** [comment]
Ah I see "hopefully once merge", good to go 👍

**Comment by mixonic** [comment]
@zeppelin I'm seeing build failures during `bundle exec middleman build --verbose` :-( Seems like a variables are not defined

**Comment by mixonic** [comment]
Pushed a revert in https://github.com/emberjs/website/commit/798bfd7b8a7489eaa24d4bca9cc6da0e55b52c61

**Pull request merged**
