### PR TITLE
Added muffin to users

### PR DESCRIPTION
**Pull request by leo**
My most recent project (http://muffin.cafe) is built on top of Ember 😊 

I also sent out the email to listing@emberjs.com (like mentioned in the `users.yml` file) but I got a "Delivery to the following recipient failed permanently" message back.

### CODE REVIEW

**Comment by wifelette** [comment]
Heya—

Don't think we've seen the email come through yet, checked spam as well. Can you resend and then this'll be good to go?

**Comment by leo** [comment]
@wifelette Sadly, I'm not even able to send the email. I mean, I am, but I always get this error:

screen shot 2016-05-09 at 20 58 29

**Comment by wifelette** [comment]
Wait, are you saying you never successfully sent the initial email you referenced?

I just ran several tests from other emails and domains and was unable to reproduce this. We haven't had any other error reports. Probably need someone with more impressive email debugging skills to help me figure this one out... / cc @locks

**Comment by leo** [comment]
@wifelette Yep! I'm assuming that Google simply hates emails from iCloud addresses (had issues with that before). So I'm going to resend it from my Gmail addresses, can you verify that it worked?

**Comment by leo** [comment]
@wifelette Haha... Just got the exact same error again! 🙈

**Comment by wifelette** [comment]
Good to go once this is rebased!

**Comment by leo** [comment]
@wifelette Done! :blush:

**Pull request merged**
