### PR TITLE
Added HealthSparq to users

### PR DESCRIPTION
**Pull request by jneurock**
Will email for listing with PR # shortly

### CODE REVIEW

**Comment by twokul** [comment]
cc @wifelette

**Comment by wifelette** [comment]
Needs to be rebased, but is otherwise good to merge :)

**Comment by twokul** [comment]
@jneurock do you mind rebasing?

**Comment by jneurock** [comment]
Should be done

**Comment by stefanpenner** [comment]
:+1:

**Comment by jneurock** [comment]
Thanks!

**Pull request merged**
