### PR TITLE
Update the home page examples & the build app to use Ember 2.0 

### PR DESCRIPTION
**Pull request by kiwiupover**
Updated ember-middleman to version 0.0.15 which upgraded Ember to 2.0.2

Also updated the build ember app.
`bind-attrs` be gone. Also removed a rogue `@each` 
removed prototype extensions from both the build app as well as the inline examples. 

Closes #2322 

Cheers

### CODE REVIEW

**Comment by jheth** [comment]
+1

**Comment by krisselden** [comment]
@trek can you review?

**Comment by rwjblue** [comment]
Looks good

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
