### PR TITLE
update to the teams page

### PR DESCRIPTION
**Pull request by MelSumner**
**Done:**
- updated the data so names can be sorted by last name
- separated teams into section
- removed subteams reference, replaced it with team name headings
- added Github and twitter to everyone
- removed team badges (team headings take care of it)

**Still to do:** 
- [ ] need twitter handles for everyone (or plan for what to do in lieu of twitter handles)
- [ ] need descriptor sentences for each team- 1-2 sentences that explain what each team is primarily responsible for.  I'm going to tag a few people in each team- please weigh in on the comments if you have a suggestion.  
  - Ember CLI (@kategengler @kellyselden @Turbo87) 
  - Ember Data (@dgeb @igorT)
  - Learning Team (@locks @jenweber @acorncom)
- [ ] need details for each team (repo for the public meeting notes, when do they meet, etc)

### CODE REVIEW

**Comment by wifelette** [comment]
I'm assuming this is an interim state and that we'll iterate :)

That said, the new prominence for the other teams makes the page kinda long. Thoughts on shrinking all the people a bit, maybe shifting to 4-6 on a line that way? We can also make the alumni smaller than the rest, similar to how the subteams _used_ to be. Thoughts?

**Comment by MelSumner** [comment]
@wifelette yes very much meant for iteration (and discussion!). 
I made some tweaks based on your feedback.

**Comment by wifelette** [comment]
Better, thank you!

**Comment by MelSumner** [comment]
Going to move the remaining issues into their own ticket so we can ship this first iteration and also resolve #3257 in the process.

**Pull request merged**
