### PR TITLE
Core Team page redesign

### PR DESCRIPTION
**Pull request by sandraor**
I've implemented the Team page redesign started by @max. Here's a preview:

team-redesign

cc @wifelette

### CODE REVIEW

**Comment by wifelette** [comment]
Thanks for your help getting this shipped @sandraor, and thanks again @max for your hard work too!

**Comment by max** [comment]
Oh, wow! This looks excellent. Thanks @sandraor.

**Comment by wifelette** [comment]
@max We haven't lost the middle section, it's just temporarily commented out :) Gotta collect the current roster for that section, page will look even better once it's added back in.

**Comment by mixonic** [comment]
:clap: very nice :-)

**Pull request merged**
