### PR TITLE
Responsify Header

### PR DESCRIPTION
**Pull request by namack**
This PR makes the header responsive in a consistent way with the guides. It also brings over the base SASS (variables, components, bourbon, neat, base) used in the guides for future "responsification".

### CODE REVIEW

**Comment by namack** [comment]
This inadvertently changed some font choices in the API section. Closing for now.

**Comment by acorncom** [comment]
@namack @ryanlabouve Could you guys work on joining forces on these changes?  It's awesome to have you both working on improving the website, just want to make sure we don't duplicate efforts ;-)

**Comment by acorncom** [comment]
@namack See https://github.com/emberjs/website/pull/2496 for some stuff that Ryan has been working on recently

**Comment by namack** [comment]
Definitely! What would be the best way to incorporate both sets of changes? @ryanlabouve would you like to add your changes to `stylesheets/components/_footer.scss` and "bourbonize" them?

Let me know what you guys this is the best way forward.

**Comment by mixonic** [comment]
@namack this doesn't share the styles between repos correct? It duplicates them?

**Comment by namack** [comment]
Correct - it would be best to share styles though, any ideas on the best way to do this?

**Comment by mixonic** [comment]
incremental steps seem ok- getting aligned is a good step forward :+1: I'd like to get @ryanlabouve's immediate fixes merged and live, and then assert that this introduction of bourbon is visually impact-free. That is the goal, right? To preserve the existing visual style completely while getting the CSS implementations aligned?

**Comment by namack** [comment]
Yep, exactly :grinning:

**Comment by namack** [comment]
This would make the header match the current styling of the guides header - not the rest of the page headers.

**Comment by namack** [comment]
I'm in the process of pulling out all of the shared styles between the guides and website [into a gem](https://github.com/namack/emberjs_website_styles), so we can close this and wait until the gem can be integrated.

**Comment by ryanlabouve** [comment]
hey @namack! You might check out https://github.com/emberjs/website/pull/2477. I have ported the header from the guides already. Currently, it's dependency free from bourbon and friends as a temporary step towards moving to all the base styles on guides and has been confirmed to provide a seamless transition from guides and back (barring a few details mentioned in website/2477).

Currently, any page that has the frontmatter `resopnsive: true` will opt in to the responsive header. You can check out http://emberjs.com/ember-community-survey-2016/ for an example.

**Comment by namack** [comment]
Ah sweet! Didn't see that PR, great work. I had seen the `responsive: true` option, and agree that it's best to only have a responsive header if the rest of the page is also responsive. So let's close this PR - what is your plan moving forward to make the rest of the pages responsified? How can I help?

**Pull request closed without merging**
