### PR TITLE
Update about.html.erb

### PR DESCRIPTION
**Pull request by locks**
We've been talking about nudging the messaging around Ember, and a slide in the keynote kicked off a particular thread:
screen shot 2018-04-16 at 15 00 40

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems like a non-trivial change. Should get feedback from @wifelette, @wycats, and/or @tomdale...

**Comment by locks** [comment]
I sent this PR to open discussion, so please let's discuss instead of talking about discussing.

**Comment by MelSumner** [comment]
I vote yes.

**Comment by ebryn** [comment]
I personally liked the reframing in the keynote and thought it was a nice update.

**Pull request merged**
