### PR TITLE
Add documentation about ember-2-legacy addon

### PR DESCRIPTION
**Pull request by thoov**
Fixes: emberjs/ember-2-legacy#38

cc @locks

### CODE REVIEW

**Comment by locks** [comment]
@rwjblue the team will be discussing it tomorrow at the meeting, there's some opinions regarding where the prose should go 😁

**Comment by thoov** [comment]
@locks Any update on this?

**Comment by jenweber** [comment]
@thoov sorry, this was slowed down a little by discussion about where the messaging should go. We'll probably duplicate this in a couple more places to make sure everyone gets the memo 😄

**Comment by jenweber** [comment]
Merged, closes emberjs/ember-2-legacy#38

**Comment by thoov** [comment]
Thanks @jenweber

**Pull request merged**
