### PR TITLE
No uppercase text transform for API headers

### PR DESCRIPTION
**Pull request by maxcal**
Improves the readability of the API docs by removing the uppercase text transform. See #2276

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me.

@mixonic / @trek / @emberjs/guides-managers - Any thoughts/objections?

**Comment by michaelrkn** [comment]
cc @locks

**Comment by mixonic** [comment]
I am +1.

**Comment by trek** [comment]
Thanks! I've always disliked this.

**Pull request merged**
