### PR TITLE
Ember Data Tagged builds promoted

### PR DESCRIPTION
**Pull request by koriroys**
Ember Tagged releases has grown long over the last two years, and Ember Data Tagged
Releases require scrolling WAAAAAAAY down the page. This pull request hopes to improve
the visibility of Ember Data Tagged Builds by moving it to it's own list item.

It would be nice if the ember s3 bucket had separate prefixes for Ember and Ember Data.
As it stands now, you have to grab everything and filter it after the fact.

Before:

screenshot 2015-08-13 23 08 53

After:

screenshot 2015-08-13 23 07 17

### CODE REVIEW

**Comment by wycats** [comment]
This change will break existing URLs. Can you redirect `/tagged/*` to `/tagged/ember`?

**Comment by wycats** [comment]
Otherwise this is great!

**Comment by koriroys** [comment]
@wycats there's some gnarly code in that builds app.

**Comment by rwjblue** [comment]
> there's some gnarly code in that builds app

CONFIRM!

**Comment by koriroys** [comment]
@wycats @rwjblue I think this is ready to go.

**Comment by koriroys** [comment]
@wycats @rwjblue can this get some love?

**Comment by acorncom** [comment]
@koriroys Sorry about the delay here.  If you can get the conflicts resolved here, we'll escalate this to core next week and try to get it merged.

**Comment by koriroys** [comment]
@acorncom Works now, though for some reason it's not putting a '/' in front of the '#', so you end up with `http://192.168.1.22:4567/builds#/tagged/ember` instead of `http://192.168.1.22:4567/builds/#/tagged/ember`. Doesn't seem to affect actual navigation any, but it is a bit odd.

**Comment by rwjblue** [comment]
I think this was addressed by a recent refactor @mixonic did.

**Pull request closed without merging**
