### PR TITLE
Add note with the only breaking change in Ember 2.0: Ember.set

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by cibernox** [comment]
@mixonic @stefanpenner Brought by https://github.com/emberjs/ember.js/issues/12095

**Comment by stefanpenner** [comment]
Can you include the rationale. Proper es semantics and sanity with super in cp

**Comment by cibernox** [comment]
@stefanpenner can you remind me the problem with `super`?

**Comment by stefanpenner** [comment]
it was the same as:

```
computed('other', {
  get() { return this.get('other'); },
  set(_, v) { 
    // some code that is a setter
    return this.set('other', v); // returns the wrong thing
    // vs 
    return this._super(); // returns the right thing
   }
})
```

**Comment by rwjblue** [comment]
seems like this needs a rebase

**Pull request closed without merging**
