### PR TITLE
Redirects guides to versioned guides

### PR DESCRIPTION
**Pull request by trek**

### CODE REVIEW

**Comment by distilledhype** [comment]
<3

**Comment by joostdevries** [comment]
@trek wouldn't a redirect to `/latest` make more sense and then have `guides.emberjs.com/latest/some-page` resolve to whatever is the latest version of that page? Or is the plan to update the erb after every release?

**Comment by trek** [comment]
@joostdevries less sense, I'd imagine. 

Where would if we redirect http://emberjs.com/guides/controllers/ to in Ember 2.0?

**Comment by joostdevries** [comment]
@trek good point.

**Comment by wagenet** [comment]
Seems plausible. What about people linking with bookmarks? Should we add a JS redirect in as well like I did with middleman-alias?

**Pull request merged**
