### PR TITLE
britishgas

### PR DESCRIPTION
**Pull request by vinodhrajamuralidharan**
- [X] - Added BritishGas on ember users list

### CODE REVIEW

**Comment by wifelette** [comment]
Missing the Use field—please add it to describe how / in what app BG is using Ember :) Should be good to merge after that!

**Comment by vinodhrajamuralidharan** [comment]
@wifelette  -- Added use field

**Comment by wifelette** [comment]
Apologies... but I'm not sure that sentence is comprehensible. I can't understand what it's saying.

Examples of other explanations:
* "We use Ember to build X"
* "We use Ember for building consulting client projects"
* "We use Ember for our internal X tool"
* "X is built with Ember"

Simple please, we'll need to use this later for categorization.

**Comment by vinodhrajamuralidharan** [comment]
@wifelette - can you check now

**Pull request merged**
