### PR TITLE
Using proper options with bower install

### PR DESCRIPTION
**Pull request by morganick**
Per bowers documentation `--dev` is not an install option: http://bower.io/docs/api/#install

### CODE REVIEW

**Comment by ryansch** [comment]
:shipit:

**Comment by acorncom** [comment]
Looks like that's an issue for each channel, would you mind fixing the other Bower lines as well?

**Comment by morganick** [comment]
:wave: hey @acorncom!

**Comment by rwjblue** [comment]
Thanks!

**Comment by morganick** [comment]
Thank you :smile:

**Pull request merged**
