### PR TITLE
Adding Heroku and Ally bank to Ember-Users.

### PR DESCRIPTION
**Pull request by mikeumus**
Heroku's new dashboard and Ally.com use Ember.js! :smile: :+1:  
(or so [wappalyzer's chrome extension](https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg) tells me)

### CODE REVIEW

**Comment by rwjblue** [comment]
Adding users to the list here is generally done by folks from the company being added.  As mentioned in the YAML file we need an email contact for each user to be added.

Are you representing Heroku and Ally here?

**Comment by mikeumus** [comment]
I am not, as I explained in my requested email to listing@emberjs.com. Just thought it was really cool that they use Ember and thought others would like to see it as well. I understand. I have no such friends there either so, alas, it'll be our secret that they're using ember. ;)

**Comment by mikeumus** [comment]
Seems legit: https://blog.heroku.com/archives/2014/8/5/new-dashboard-and-metrics-beta

Reaching out to some people, :pray:  :four_leaf_clover:

**Comment by wifelette** [comment]
If we can find some people who *do* work there to give us the thumbs up, a-okay. If not we'll probably close this for now, just in the interest of not representing someone who might not be okay with it :)

If you happen to know anyone who works at Heroku or Ally, feel free to cc them here. I'll do that too.

*Ally*:
@nathanhammond 

*Heroku*
@paulelliott 
@JackCA 
@appleton

**Comment by paulelliott** [comment]
Are you just asking if you may add Heroku to http://emberjs.com/ember-users? That's ok with me.

**Comment by wifelette** [comment]
Fantastic, thanks @paulelliott! 

@mikeumus —can you separate these so we can merge then separately?

**Comment by JackCA** [comment]
@wifelette One sec, I'm getting confirmation from our PR/Marketing people -- but it will most likely not be a problem!

**Comment by nathanhammond** [comment]
Can confirm Ally does use Ember, can't confirm whether or not it's kosher to add to this list. Dropping a line to the Brand team.

**Comment by wifelette** [comment]
Thanks you all :) We'll await your responses.

**Comment by JackCA** [comment]
(avoiding another PR) @mikeumus can you swap our or logo [with this one](https://www.dropbox.com/s/huphgmuxfouzfzv/heroku-logotype-horizontal-purple.svg)?

Other than that, we're good to go!

**Comment by mikeumus** [comment]
An SVG! Indeed good sir. :laughing:

**Comment by wifelette** [comment]
@nathanhammond Any word?

**Comment by nathanhammond** [comment]
@wifelette Re-pinged parties involved. :)

**Comment by wifelette** [comment]
If someone wants to separate the two and rebase, I'll at least get the Heroku one merged, so it's not waiting on Ally :)

**Comment by trek** [comment]
#2071 adds heroku. We can re-open for Ally if/when we hear back

**Pull request closed without merging**
