### PR TITLE
Hover issue social links in footer #3273

### PR DESCRIPTION
**Pull request by ashokaditya**
Although, I can't verify the patch locally cause localhost:4576/guides redirects me to the production https://guides.emberjs.com/v3.1.0/

### CODE REVIEW

**Comment by jenweber** [comment]
@ashokaditya can you tell me more about the problem this tries to fix? I don't see any issues with the hover state on the social links.

**Comment by ashokaditya** [comment]
@jenweber The social links at the bottom of https://guides.emberjs.com/v3.1.0/ show underlines when hovered which is inconsistent with the rest of the website's "no underline" on hover. My patch is to fix that. But like I mention I can't verify the fix locally cause the localhost:4567/guides linke redirects me to https://guides.emberjs.com/v3.1.0/.

Please let me know if that clarifies it :)

Thanks.

**Comment by jenweber** [comment]
Oh ok, I see it now. I was looking on the Ember home page and not the guides, oops. We're launching a new app for the Guides this week (ish) and the hover issue is already fixed there. I'm going to close this PR since it's covered elsewhere, but thank you for taking the time to report/fix the issue!

**Comment by ashokaditya** [comment]
👍

**Pull request closed without merging**
