### PR TITLE
Ember 2.18 Release Blog Post

### PR DESCRIPTION
**Pull request by locks**
- [Rendered](https://github.com/emberjs/website/blob/2-18-release-blog-post/source/blog/2018-01-01-ember-2-18-released.md)
- Preview

## Sign-offs

- [ ] Ember.js (@chancancode)
- [x] Ember Data (@bmac)
- [ ] Ember CLI (@rwjblue)
- [ ] Website (@locks, @mixonic)

## Checklist

- Ember
  - [ ] Blog
  - [ ] v2.18.0
  - [ ] v2.19.0-beta.1
- Ember Data
  - [x] Blog
  - [x] v2.18.0
  - [x] v3.0.0-beta.1
- Ember CLI
  - [ ] Blog
  - [ ] v2.18.0
  - [ ] v2.19.0-beta.1

See https://github.com/emberjs/website/pull/2824/files for inspiration.

### CODE REVIEW

**Comment by locks** [comment]
Ember 3.0 betas:
- Deprecation removal
- ember-2-legacy

**Comment by rwjblue** [comment]
Ember 3.0 Beta:

* Updated blueprints (for emberjs/rfcs#232 and emberjs/rfcs#268). c
  * Can opt-in to new blueprints on older ember-source versions via [ember-qunit-nested-module-blueprints-polyfill](https://github.com/alexander-alvarez/ember-qunit-nested-module-blueprints-polyfill)
  * Can run [ember-qunit-codemod](https://github.com/rwjblue/ember-qunit-codemod) to migrate `moduleForComponent`, `moduleFor`, and `moduleForModel`.
  * Blog post with some additional info (primarily for emberjs/rfcs#232, but will likely do another post before release with emberjs/rfcs#268 info): http://rwjblue.com/2017/10/23/ember-qunit-simplication/.

**Comment by Turbo87** [comment]
Ember CLI 2.18:

- [#7385](https://github.com/ember-cli/ember-cli/pull/7385) Remove Node 7 support [@kellyselden](https://github.com/kellyselden)
- [#6955](https://github.com/ember-cli/ember-cli/pull/6955) Discover dependencies of npm-linked addons [@ef4](https://github.com/ef4)
- [#7419](https://github.com/ember-cli/ember-cli/pull/7419) Delete obsolete crossdomain.xml [@sandstrom](https://github.com/sandstrom)
- [#7443](https://github.com/ember-cli/ember-cli/pull/7443) Use `overrides` for a single `.eslintrc.js`. [@rwjblue](https://github.com/rwjblue)
- [#7455](https://github.com/ember-cli/ember-cli/pull/7455) Add eslint-plugin-ember to default linting config. [@rwjblue](https://github.com/rwjblue)

I guess the biggest user-facing change is the ESLint thing. We now only have a single `.eslintrc.js` file and that includes `eslint-plugin-ember` by default.

**Comment by Turbo87** [comment]
Ember CLI 3.0 does not have many changes yet. The most visible is for addon authors:

- [#7479](https://github.com/ember-cli/ember-cli/pull/7479) Improve default addon README [@Turbo87](https://github.com/Turbo87)

**Comment by jenweber** [comment]
@locks we might want to add the following to the removed API list. Not sure:

* Using Ember.Application.registry properties directly (this usage was private, but a [migration path](https://www.emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry) is available)

**Comment by mixonic** [comment]
FYI I have rebased and force pushed this branch on master. I'd like to preview with the final styles and a bunch has changed on master. Please use fetch and reset to update your local branch.

**Pull request merged**
