### PR TITLE
Update Billy image and url

### PR DESCRIPTION
**Pull request by jryanwestby**

### CODE REVIEW

**Comment by wifelette** [comment]
@jryanwestby Thanks for getting this in! 

The old entry you're updating is from a time before we had the `use` field—you can see it on all the more recent entries. Can you add it to yours and then this should be good to merge?

**Comment by locks** [comment]
Hey @jryanwestby, waiting on that `use` field so we can merge this :)

**Comment by rwjblue** [comment]
@jryanwestby - Ping?

**Comment by jryanwestby** [comment]
Sorry about the delay on this. I've added that use field.

**Comment by wifelette** [comment]
So close ;) Shouldn't be a product description, but a description of the Ember use. A la "Billy's main app is built with Ember."

**Comment by locks** [comment]
@jryanwestby nearly there, can you address @wifelette's latest comment so we get this puppy on the website? :]

**Comment by jryanwestby** [comment]
There we go. Thank you for your patience and sorry about the delay

**Comment by locks** [comment]
And we're off to the races!

**Pull request merged**
