### PR TITLE
defaulted the ember bootstrap to javascript

### PR DESCRIPTION
**Pull request by eibrahim**

### CODE REVIEW

**Comment by rwjblue** [comment]
@tricknotes - Can you :+1: / :-1: ?

**Comment by acorncom** [comment]
@tricknotes @rwjblue any updates here?

**Comment by locks** [comment]
repoke @tricknotes @rwjblue

**Comment by rwjblue** [comment]
Closing this for now, I am really unsure what ember-rails expects here. To move forward I'd like @tricknotes to confirm.

**Pull request closed without merging**
