### PR TITLE
Adding iLoan logo

### PR DESCRIPTION
**Pull request by albertpak**

### CODE REVIEW

**Comment by wifelette** [comment]
Heya—

I don't think we saw the email come through on this yet (just searched), as per instructions in the Yaml file :) Can be merged as soon as it does!

**Comment by albertpak** [comment]
@wifelette let me double check - i remember i sent out an email to `listing@emberjs.com` @ 2pm Central, I will resend

**Comment by wifelette** [comment]
Got it now, thanks for resending!

**Comment by albertpak** [comment]
Thank you :)

**Pull request merged**
