### PR TITLE
Add my google-site-verification

### PR DESCRIPTION
**Pull request by mansona**
This will allow me access to the Google Search Console as part of my SEO and Analytics efforts

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
@acorncom is there an official account that we can share instead of this?

**Comment by acorncom** [comment]
@sivakumar-kailasam yes, looks like I added the line above Chris’, so I’ve got access there. Will work that out tomorrow when I’m at a computer

**Comment by sivakumar-kailasam** [comment]
Great, closing this issue then

**Comment by mansona** [comment]
Sure @acorncom we should chat about getting this sorted at some point soon 👍 

The reason I opened this PR was because I'm under the impression that "accounts" don't work the same way when it comes to the search console 🤔 that may have changed or I could be very mistaken 😂

**Pull request closed without merging**
