### PR TITLE
Hide private and deprecated classes and namespaces from sidebar.

### PR DESCRIPTION
**Pull request by krisselden**
WIP

- [x] hide private and deprecated from side list
- [ ] hide from private and deprecated from list under module page (maybe just remove this?)
- [ ] hide empty classes/namespaces that had no documentation only made visible by private members (maybe just enforce this on code side?)
- [ ] make deprecated stuff styled instead of hiding (ensure deprecated 1.x is marked private)
- [ ] style private and public at top more noticeable fashion

### CODE REVIEW

**Comment by toddjordan** [comment]
cool.  Thanks for taking this on - to address issue #2452

**Comment by rwjblue** [comment]
@krisselden - It seems to me that the first entry on your checklist is valuable to land on its own.  Would you mind if we merged as is, and you can continue iterating in a new PR?

**Comment by Gaurav0** [comment]
My comments: https://github.com/emberjs/ember.js/pull/13075#issuecomment-195503189

**Comment by rwjblue** [comment]
@Gaurav0 - This PR is completely unrelated to the PR that you linked to.

**Comment by krisselden** [comment]
@rwjblue let's just start with this one.

**Comment by krisselden** [comment]
@Gaurav0 @rwjblue @toddjordan  just the sidebar hiding is complete in this and can be merged, I can move the checklist elsewhere

**Comment by toddjordan** [comment]
Yes. Will be good as a start.  I'm planning on working on a toggle this week, as well as starting some research on how to start getting the api deployed to a subdomain.

**Comment by toddjordan** [comment]
I pulled this branch, built and ran it locally, and when I click on some classes I get the following error. It doesn't happen consistently 
```
NoMethodError: undefined method `find_class' for #<APIDocs::Api:0x007fa94b068280>
	/Users/jordanto/dev/emberjs/website/lib/api_docs.rb:155:in `extends'
	/Users/jordanto/dev/emberjs/website/lib/api_docs.rb:169:in `classitems'
	/Users/jordanto/dev/emberjs/website/source/api/class.html.erb:42:in `block (2 levels) in singleton class'
	/Users/jordanto/dev/emberjs/website/source/api/class.html.erb:42:in `select'
	/Users/jordanto/dev/emberjs/website/source/api/class.html.erb:42:in `block in singleton class'
	/Users/jordanto/dev/emberjs/website/source/api/class.html.erb:-6:in `instance_eval'
	/Users/jordanto/dev/emberjs/website/source/api/class.html.erb:-6:in `singleton class'
	/Users/jordanto/dev/emberjs/website/source/api/class.html.erb:-8:in `__tilt_70182535050520'
	/Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
	/Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
	/Library/Ruby/Gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/rendering.rb:313:in `render_individual_file'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/rendering.rb:181:in `_render_with_all_renderers'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/rendering.rb:149:in `render_template'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
	/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/util.rb:41:in `instrument'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/application.rb:241:in `instrument'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/sitemap/resource.rb:100:in `render'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/request.rb:210:in `block in call!'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/request.rb:209:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/request.rb:209:in `call!'
	/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/lib/middleman-core/core_extensions/request.rb:195:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by rwjblue** [comment]
Hmmmm. Not sure of the top of my head what would cause this. 

@krisselden - Do you think you might have a chance to take a look? If not, I can revert and restore the branch so we can dig in when we have time...

**Comment by rwjblue** [comment]
reverted (we couldn't deploy)

**Pull request merged**
