### PR TITLE
typography: more spacing below h1 and h2

### PR DESCRIPTION
**Pull request by jenweber**
This is a tiny fix for something that bugs me - I think heading text looks more balanced when it has greater spacing than a typical line. Let me know what you think. I had a designer look through and he said that the spacing I'm adding should not be applied to other h2s throughout the site, just the home page, which is what I've done here.

### After:
screen shot 2018-04-01 at 7 36 47 pm

screen shot 2018-04-01 at 7 36 39 pm

### Before
screen shot 2018-04-01 at 7 37 29 pm

screen shot 2018-04-01 at 7 37 22 pm

### CODE REVIEW

**Comment by MelSumner** [comment]
@jenweber it's already in PR #3249

**Comment by wifelette** [comment]
While you're in here, are we also able to fix the business of the logos being skewed to the bottom in the carousel?

**Comment by MelSumner** [comment]
@wifelette fixed with https://github.com/emberjs/website/pull/3266

**Comment by jenweber** [comment]
@MelSumner done! However by putting this rule in base_typography, it now affects all h2s, while I was initially targeting only the home page. Have a look and see if this is an improvement. It especially has an impact on the blog headings (list view and individual view). Thanks!

**Comment by MelSumner** [comment]
I'd rather add a margin-bottom to the h2 across the whole site and remove the hr. We can switch to a border bottom (or just leave the line out entirely) for the blog; I'm trying to avoid doing custom implementations to each page, since this is why the CSS is a mess already and felt like we extracted the typography styles (across the board) out as a first step. What do you think?

**Comment by MelSumner** [comment]
@jenweber since we mostly resolved this issue in other PRs, I'm going to close this PR. please re-open if you don't feel like the issue was adequately addressed. 👍

**Pull request closed without merging**
