### PR TITLE
The Ember Times - Issue No. 73

### PR DESCRIPTION
**Pull request by tylerturdenpants**
Ideas, feel free to add to list or claim!

- [x] Want to test React Hook API in Ember > 3.4? https://github.com/lifeart/hooked-components Pure functional components in Ember with implemented React Hooks API using Ember Custom Component Manager. (could check in with @lifeart, who already added https://github.com/emberjs/website/pull/3684#issuecomment-437758402 below - thank you!) (:lock: @jessica-jordan) we'll write about hot reloading from comment below instead
- [x] Last Call for EmberConf Cfp (🔏 @jessica-jordan)
- [x] 24pullrequests.com ?
- [x] [EmberFest Videos](https://www.youtube.com/playlist?list=PLN4SpDLOSVkSB9034lDNdP1JoNBGssax9) are up! Deep dive into these talks? Could be multiple writeups. (Note: We touched on the GraphQL talk, based on their blog post, a few issues ago.) See also #ember-fest on Discord. (🔒 @kennethlarsen )
- [x] [eslint-plugin-ember v6.0.0](https://twitter.com/TobiasBieniek/status/1062700572757946368) (🔒 @chrisrng )
- [x] DecEmber (:lock: @MelSumner)

Ideas for next week instead:

- [ ] https://github.com/emberjs/rfcs/pull/395 (this is ready to be written about in this edition)
- [ ] Check https://github.com/jessica-jordan/whats-new-in-emberland (roundup of all the PRs in emberjs and ember-learn repos)
- [ ] EmberCamp talks, deep dive? http://embercamp.com/ and https://github.com/ember-chicago/ember-camp-2018-notes Maybe we wait for the talk videos to be published? Keep an eye on #ember-camp in Discord.
- [ ] Include summary from @pixelhandler / #issue-triage in Discord?
- [ ] More EmberFest?
- [ ] More DecEmber?

### CODE REVIEW

**Comment by lifeart** [comment]
ember-ast-hot-load  - https://github.com/lifeart/ember-ast-hot-load - new attempt to bring components hot-reloading into ember ecosystem

**Comment by tylerturdenpants** [comment]
@lifeart 🙏.  A small write-up would be 💯.

**Comment by lifeart** [comment]
@tylerturdenpants done

**Comment by amyrlam** [comment]
@lifeart thanks again for the writeup on your addon, much appreciated! 🙏 

Keep the suggestions coming! You can always comment on PR's here or [#support-ember-times](https://discordapp.com/channels/480462759797063690/485450546887786506) on Discord

**Pull request merged**
