### PR TITLE
Adding Roofstock to companies using Ember

### PR DESCRIPTION
**Pull request by msreekm**

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
@msreekm if you could resize the image & resolve the conflicts in your PR, this would be good to merge :)

**Comment by msreekm** [comment]
ok fixing size.

**Comment by msreekm** [comment]
please review the new pull request ,updated logo and resolved conflict!

**Comment by sivakumar-kailasam** [comment]
Thanks for the PR @msreekm 🎉

If there's a blog post that you/your company has written about your experience with Ember do share it with us 🙂. 

Hope to see you in other PRs in the future! 👋

**Pull request merged**
