### PR TITLE
Update suggested fix for deprecation warning

### PR DESCRIPTION
**Pull request by backspace**
As suggested by @Gaurav0 in #2615.

### CODE REVIEW

**Comment by backspace** [comment]
During the LIVE ACTION PR CODE REVIEW SESSION, the result of some discussion was that there should be clarification here on how to fix this in a more desirable way, by rewriting your code to not produce double-renders. This suggestion of how to work around the warning if you _really_ need to double-render can remain, but should be marked as a last resort.

I’ll return to this soon!

**Comment by locks** [comment]
I think of the proposed solution as more of an anti-pattern than a pattern. I'm closing this one, feel free to open another one when you return to the subject :)

**Comment by Gaurav0** [comment]
@locks It would have been helpful if an acceptable solution is posted on the issue. "Rewrite your code so that no double render is necessary" is not a mechanical operation, and IMO means the deprecation itself should be reversed unless there is a way to fix it mechanically.

**Comment by rwjblue** [comment]
@Gaurav0 - Nothing about the concept of a deprecation infers or suggests that they are all simple fixes. Many are complicated and involve programming model shifts (moving away from views in general is like this).

**Comment by Gaurav0** [comment]
@rwjblue Not what was said: https://github.com/emberjs/rfcs/pull/56/files




-------- Original message --------

**Comment by mixonic** [comment]
I'm not sure what is happening here.

* The deprecation guide here is incorrect. It needs updating.
* The author proposed a change and has received feedback, will follow up.
* The issue was closed and I'm unsure of the rational- this is just pending new work. I'll chat with @locks and see what was an anti pattern about the proposed route forward.
* The thread is being hijacked over some suggestion the deprecation be removed? Seems unrelated.

Please try to keep our scope on improvements to the documentation here. It is really needed, and I don't want to lose that end goal. Thanks!

**Comment by Gaurav0** [comment]
@mixonic If there is no way to avoid a deprecation warning that we don't consider an antipattern, why do we have it deprecated? Why can we not correct an error on the website with a solution that works when there is no solution you guys like?

**Comment by ef4** [comment]
@Gaurav0 there is no requirement that clearing deprecations is mechanical. That's why they are deprecations and not breaks. It's expected that sometimes they require real work, which is why we keep deprecated code around so long.

People who are upset by the message but don't have the time to fix it right away should be pointed toward ember-cli-deprecation-workflow.

Using your own run loop doesn't solve the problem, it just hides it, so it is equivalent to ember-cli-deprecation-workflow anyway. The real problem here is expensive render loops that are hurting app performance and causing data flow loop bugs.

**Comment by Gaurav0** [comment]
@ef4 @mixonic 

In my experience, if you can't move the offending `set` to init because you are setting a value based on information you only have after render, there is no clean way to rewrite your code to avoid a double render. There really is no solution other than the one I suggested, which is why I think this deprecation should never have been made.

This deprecation message is extremely confusing to newcomers to Ember as I experienced this morning. Furthermore, it happens extremely often. I am really upset that we can't fix the guides to at least give some way out that works.

**Comment by ef4** [comment]
We didn't add that message to make things harder, we did it to make things easier. Without the messages, all those newbies are just shooting themselves in the feet, because they will wonder why their app is so buggy and have no way of figuring out what's going on. 

It's a question of complaining early so the problem can be found, instead of failing silently. Those are the options. Make it magically work is not actually an option. It never worked reliably, because it can't without nuking performance for everyone.

I absolutely agree we need better teaching for how to react to the warning. The guide could walk through multiple scenarios and how to fix each one. Using a separate render loop _is_ one of those solutions but only in rare cases where you are truly measuring the output of the previous render. Newbies almost always have simple data flow problems that would be made worse by an extra run loop, not better.

**Comment by Gaurav0** [comment]
> The guide could walk through multiple scenarios and fix each one.

Could someone describe a single nontrivial scenario where one could rewrite code to avoid a double render? (If the `set` can be cut and pasted to `init` or `didReceiveAttrs` that I would consider trivial.)

**Comment by ef4** [comment]
What does trivial have to do with it? I already agreed it is non-trivial. If there was a trivial transformation we would just do that automatically.

**Comment by Gaurav0** [comment]
You wanted me to walk through scenarios. I'm trying to figure out if there are any besides the obvious ones.

**Comment by ef4** [comment]
Sorry, I misread your comment. :-p

**Comment by ef4** [comment]
One of the common cases I see is a computed property getter that calls `set`. You can always replace the value being set with a separate computed property that depends on the one that used to be doing the `set`.

Another case is when there is a list of items and a currently highlighted item, and the user tries to store `isHighlighted` as a property on each item in the list, forcing them to try to make that data flow upward again through the parent. The fix is to move that state to the parent in the first place by storing a `highlightedItem` property there that always flows down to the children.

**Comment by Gaurav0** [comment]
@ef4 Thanks. I'll put up another PR for this.

**Pull request closed without merging**
