### PR TITLE
added Blackbell user to the users list

### PR DESCRIPTION
**Pull request by antonbavykin1991**

### CODE REVIEW

**Comment by wifelette** [comment]
Heya—

Excited to add your team to the page! Two small things: 

First, logo should have a transparent background in case something else changes around it (like how we just adjusted the precise details of the white-ish pill the logos are on), and second, reminder to send the email as per the instructions in the yml file so we can then merge this :)

Thanks!

**Comment by wifelette** [comment]
+1 on the image! I haven't seen the email come through though, you sure it went through?

**Comment by antonbavykin1991** [comment]
Yes, you should see mail from david@blackbellapp.com

**Comment by wifelette** [comment]
Found it! Was buried in my spam box for some reason <3 Thanks much!

**Pull request merged**
