### PR TITLE
[WIP] Small tweaks to the bind-attr deprecation details based on feedback.

### PR DESCRIPTION
**Pull request by workmanw**
Based on feedback in #2320. Please do not merge yet, I'm waiting to hear back from @mixonic on another item.

### CODE REVIEW

**Comment by rwjblue** [comment]
@mixonic - Did you still have feedback here?

**Comment by workmanw** [comment]
@mixonic @rwjblue Happy to do whatever is necessary. Documentation isn't really my strength :). Maybe it doesn't matter too much since it [hopefully] won't be a high traffic piece of documentation like the guides?

**Comment by mixonic** [comment]
@workmanw this is great, thank you and sorry I didn't get to it earlier. I'll make any additional tweak directly, they are so small the back and forth isn't worth it :wink:

**Comment by workmanw** [comment]
@mixonic Thanks! Cheers!

**Pull request merged**
