### PR TITLE
Added subteams

### PR DESCRIPTION
**Pull request by wifelette**
This could surely be prettier, but this'll get us started for now :) I only added a few folks whose headshots were easy to grab. Missing folks should add themselves. I _think_ this is everyone missing:

- [x] @trabus (CLI)
- [x] @nathanhammond (CLI)
- [x] @kellyselden (CLI)
- [x] @pangratz (Data)
- [x] @wecc (Data)
- [x] @fivetanley (Data)

(List pulled from the slides in the EmberConf keynote).

Things I'd like someone else to add:
- [x] Sort the list so it's alphabetized by first name (because first and last names are one field here)

### CODE REVIEW

**Comment by nathanhammond** [comment]
1. I'm @nathanhammond everywhere.
2. Headshot: https://www.dropbox.com/s/hxkhs0vait6v34s/avatar2.jpg?dl=0

Should probably also add #anchor links to subteams.

**Comment by acorncom** [comment]
I'd be inclined to group folks by team, to make it easier to link to from the various repos (as seen on the Rust website: https://www.rust-lang.org/team.html)  Not sure how we should sort teams, possibly alphabetically?

**Comment by wecc** [comment]
I've created PR #2551

**Comment by fivetanley** [comment]
@wifelette done and checked off! Thanks!

**Comment by locks** [comment]
I took the liberty of adding Mr. Selden to finish off the PR.

**Comment by kellyselden** [comment]
Thank you @locks!

**Pull request merged**
