### PR TITLE
Add upcoming deprecations

### PR DESCRIPTION
**Pull request by locks**
Complements https://github.com/emberjs/ember.js/pull/14590.

### CODE REVIEW

**Comment by serenaf** [comment]
Original PR for reference :) https://github.com/emberjs/ember.js/pull/14590

**Comment by serenaf** [comment]
@locks According to this https://www.emberjs.com/blog/2018/01/01/ember-2-18-released.html#toc_changes-in-ember-js-2-18 it is since 2.18.0 and until 3.5.0

**Comment by jenweber** [comment]
@locks can you remove backticks around the id? It is a small thing but makes future CSS easier. Also while you're at it, can you promote `Ember 2 legacy` up a level, so three `###` instead of four? It ought to be its own section now that I look at it.

I totally used `targetObject` in my apps. Oops.

**Comment by locks** [comment]
@jenweber done

**Comment by jenweber** [comment]
I noticed an issue with using backticks in the deprecation title too, but it's a styling problem that affects other listings so I'll open a separate PR/Issue

**Pull request merged**
