### PR TITLE
update greenfield logo on company list

### PR DESCRIPTION
**Pull request by thomascchen**

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good! But I don't see this on greenfieldhq.com (I still see the black one in the title area)...

@mikepmunroe - Look good to you?

**Comment by mikepmunroe** [comment]
Confirmed. New site development is in process and will have the new logo.

**Comment by rwjblue** [comment]
Thanks @mikepmunroe, just wanted to make sure :dancer: :dancer: :dancer:

**Comment by mikepmunroe** [comment]
:100: You're the man!

**Pull request merged**
