### PR TITLE
Add aisler to list of ember users.

### PR DESCRIPTION
**Pull request by Libermentix**
new pull request as discussed in #2130 with @wifelette

### CODE REVIEW

**Comment by wifelette** [comment]
This needs to be rebased now, but also, see my previous comment about whitespace. Did you stage this with the logo this size? I see a tiny amount of whitespace, so it might be good, but just making sure you took a look at it.

**Comment by Libermentix** [comment]
@wifelette Yes I did. It should be fine. Thanks for your advice and sorry for the hassle ;-)

**Comment by wifelette** [comment]
Fantastic :) And no hassle... still needs to be rebased so we can merge though :p

**Comment by Libermentix** [comment]
@wifelette I think i managed it now ;-) Had to dig into merging/rebasing before.

**Comment by wifelette** [comment]
Yay! All good to go now :)

**Pull request merged**
