### PR TITLE
New Company, Teem

### PR DESCRIPTION
**Pull request by tomoguisuru**
# What?
Update to add Teem to the users page

### CODE REVIEW

**Comment by wifelette** [comment]
Howdy @tomoguisuru 

The logo doesn't look to be the right dimensions, can you take a look and verify or update? This should otherwise be good to go once that's sorted!

**Comment by tomoguisuru** [comment]
@wifelette , I've updated the image. Let me know if there is anything else

**Comment by locks** [comment]
Hi @tomoguisuru, thanks for updating but the dimensions aren't quite right. As per [the instructions](https://github.com/emberjs/website/blob/master/data/users.yml#L10-L13):

> The size of the space you're filling is max 210 x 103. To best control appearance, submit an image this exact size that already includes the whitespace you want. To support high-resolution displays, consider submitting your image at twice this resolution with dimensions of 420 x 206.

You can make your logo 420x206px if you want to support high-resolution displays, but make sure you have sufficient whitespace around the actual logo. See the [other images](https://github.com/emberjs/website/tree/master/source/images/about) in the catalog for reference!

**Comment by tomoguisuru** [comment]
@locks, I've updated the image to 420x206 matching the spacing from other logos

**Pull request merged**
