### PR TITLE
Add @mmun to the team page

### PR DESCRIPTION
**Pull request by mmun**
Looks like this:

screen shot 2015-06-23 at 3 22 47 pm

### CODE REVIEW

**Comment by rwjblue** [comment]
FINALLY

**Comment by mmun** [comment]
:dancer:

**Comment by wifelette** [comment]
ZOMG. IT'S FINALLY REAL! :grin:

**Comment by stefanpenner** [comment]
A wild mmun appears!

**Comment by igorT** [comment]
:heart:

**Pull request merged**
