### PR TITLE
Clarify usage of `id()` and `ids()` for references

### PR DESCRIPTION
**Pull request by pangratz**
This updates the code samples in the blog post, which are misleading.

This addresses emberjs/data#4355.

@adam-knights what are your thoughts here?

### CODE REVIEW

**Comment by adam-knights** [comment]
Yes thats awesome. :) Thanks for all your work on this too.

**Comment by adam-knights** [comment]
The same example can be found in the 2.4 blog post too btw https://github.com/emberjs/website/blob/master/source/blog/2016-03-13-ember-data-2-4-released.md

**Comment by pangratz** [comment]
Awesome catch @adam-knights 👀  👍  I will update this PR.

**Comment by mixonic** [comment]
Thanks :-)

**Pull request merged**
