### PR TITLE
Remove "new" text from Job Board

### PR DESCRIPTION
**Pull request by locks**
- [x] Remove text
- [x] Update graphic

### CODE REVIEW

**Comment by MelSumner** [comment]
@wifelette please have your graphics person please update the job board graphic to remove the "new" part, thank you!

**Comment by wifelette** [comment]
I don't seem to have the original art file, so request sent :)

**Comment by wifelette** [comment]
ember_jobboard_callout_042018

**Comment by wifelette** [comment]
Can't do it myself right this minute, apologies, but there's the updated file if someone else wants to have at it :)

**Comment by knownasilya** [comment]
Any chance we could just remove this banner?

**Comment by wifelette** [comment]
I don't love the current design, but we still need a prominent link to it. Totally open to other ideas if someone with the design chops wants to pitch some alternatives!

**Comment by MelSumner** [comment]
Thank you @locks <3 :+1:

**Pull request merged**
