### PR TITLE
Clean up examples in about page

### PR DESCRIPTION
**Pull request by locks**
We're working towards a cleaner look.
Instead of having (outdated) code samples with little context,
we expect interested parties to check out the getting started guide.
We should also make sure the getting started is smooth sailing.

### CODE REVIEW

**Comment by wycats** [comment]
:+1:

**Comment by stefanpenner** [comment]
whats holding up the merge?

**Comment by locks** [comment]
@stefanpenner was waiting for someone else on the learning team to 👀, but we can merge.

**Comment by acorncom** [comment]
@locks I'm ambivalent about the change, but don't mind doing so.  If we're going to do this, seems like we should remove the Ember app imported here https://github.com/emberjs/website/tree/master/source/javascripts/app/about and the `ember-middleman` Gem usage (seen in the update here https://github.com/emberjs/website/pull/2852)?

**Pull request merged**
