### PR TITLE
Don't suggest to install ember globally.

### PR DESCRIPTION
**Pull request by wolframkriesing**
Suggest not to install ember globally but just for you project locally, to prevent version problems with multiple projects and allowing upgrading individually.

### CODE REVIEW

**Comment by rwjblue** [comment]
When installed globally ember-cli properly defers to whichever version of ember-cli the current project is using, and only falls back to using the global version if you are not inside of an existing ember-cli project. 

There are no issues with having a different version in multiple projects, or having different global vs local versions.

**Comment by wolframkriesing** [comment]
Everywhere it's suggested to prevent installing any npm package globally, from what you answer this is different in ember?

**Comment by rwjblue** [comment]
There are many packages that are supposed to be installed globally.  `grunt-cli` and `gulp` are a couple examples of CLI based packages that recommend usage globally. They both also happen to have similar functionality to what I described above: they use the locally installed version of the package in a project.

**Comment by wolframkriesing** [comment]
thanks for clarification

**Pull request closed without merging**
