### PR TITLE
Feature: Indicate guest or syndicated blog post

### PR DESCRIPTION
**Pull request by pbishop16**
First-time contributor.
Addresses #3049

### CODE REVIEW

**Comment by locks** [comment]
Thanks for the contribution @pbishop16, will try to review these changes soon!

**Comment by MelSumner** [comment]
@pbishop16 thank you! Do you happen to have a screenshot? thank you!

**Comment by pbishop16** [comment]
@MelSumner Sorry about that, I tossed them in the issue. Here you go. Will adjust as necessary.

image

image



Added the below to the blog post page
---

*Top of blog post*
image

*The original url for a syndicated post:*
image

**Comment by pbishop16** [comment]
@MelSumner Absolutely will do. Thank you.

**Comment by MelSumner** [comment]
@locks @pbishop16 I'm approving the PR so we can get it in, and we'll iterate if needed.

**Pull request merged**
