### PR TITLE
add AISLER to list of ember users.

### PR DESCRIPTION
**Pull request by Libermentix**

### CODE REVIEW

**Comment by kmiller915** [comment]
Email received. cc @wifelette

**Comment by wifelette** [comment]
The logo is incorrectly sized. Needs to be fixed, and then the PR rebased, most likely.

**Comment by Libermentix** [comment]
what size do we require here? 
Is it sufficient whitespace?

**Comment by wifelette** [comment]
210 x 103 is the space the logo will occupy, so something less than that—ideally you add in the whitespace around it so you're controlling how much of the space your logo fills and it looks the way you want it to :) The previous submission ended up super stretched.

I'm about to commit a change to the file so this info is now provided up top with the rest of the instructions.

**Pull request closed without merging**
