### PR TITLE
Redirect guides to v2.0.0

### PR DESCRIPTION
**Pull request by josemarluedke**

### CODE REVIEW

**Comment by josemarluedke** [comment]
Possibly fixes #2310.

**Comment by josemarluedke** [comment]
ping.

**Comment by acorncom** [comment]
@wifelette I think this would be fine to merge here ...

**Comment by wifelette** [comment]
I think @michaelrkn had some thoughts on this in the last call?

**Comment by michaelrkn** [comment]
What we really need is https://github.com/emberjs/guides/issues/604 so that we don't have to keep updating this, but at least this is better than how it was before. Thanks @josemarluedke!

**Pull request merged**
