### PR TITLE
DEPRECATION: Ember.MODEL_FACTORY_INJECTIONS

### PR DESCRIPTION
**Pull request by stefanpenner**
ember's PR: https://github.com/emberjs/ember.js/pull/15204

- [ ] needs someone with skills with wording to review...

### CODE REVIEW

**Comment by stefanpenner** [comment]
@locks ping ping

**Comment by locks** [comment]
@stefanpenner something that's tripping me up a bit, where's the upgrade path? Do you not need to update anything else other than remove the flag?

**Comment by rwjblue** [comment]
Confirm. The flag just doesn't do anything.

**Comment by locks** [comment]
:shipit:

**Pull request merged**
