### PR TITLE
For EmberTimes No. 71: Add Tree-Shaking Help Wanted CTA

### PR DESCRIPTION
**Pull request by jessica-jordan**
Related to #3660

### CODE REVIEW

**Comment by lifeart** [comment]
https://github.com/kellyselden/ember-cli-tree-shaker addon for it

**Comment by tylerturdenpants** [comment]
@jessica-jordan I agree with @lifeart about https://github.com/kellyselden/ember-cli-tree-shaker but with caution. The add on is experimental, so we should probably state as such.

**Comment by tylerturdenpants** [comment]
@jessica-jordan I’ll  merge after I get your feedback

**Comment by jessica-jordan** [comment]
@liferart @tylerturdenpants Thank you for the suggestion, updated! :sparkles:

**Pull request merged**
