### PR TITLE
Added Global Ember Meetup to meetups page

### PR DESCRIPTION
**Pull request by taras**

### CODE REVIEW

**Comment by wifelette** [comment]
@taras Where do the map coordinates for this point? I can't pull down to stage right now, but I plugged it into an online lat/long map and it seemed to think they were invalid coordinates.

**Comment by taras** [comment]
The coordinates are pointing into the middle of North Atlantic ocean. I'm not sure what else to use :)

**Comment by wifelette** [comment]
Let's call the category Online, not Global, and leave it off the map altogether :)

Gotta make sure that omitting that info from the Yaml file doesn't blow anything else up though, and correct if so. Please verify and update PR and we should be good to go!

**Comment by taras** [comment]
I need to give it some "location" which is used as a name. What should I use there?

**Comment by wifelette** [comment]
Ah, you mean because if Online is the category, having the name of the specific meeting be Online is repetitive. Hmmm.

I'm not sure. The idea is that there may be more online meetups in the future. But I'm unsure how you'll each differentiate yourselves. And the listing design is mostly optimized for short-form names.

Ideas?

**Comment by wifelette** [comment]
Closing due to inactivity.

**Comment by acorncom** [comment]
To clarify, we're closing this pull request due to inactivity, not because we wouldn't be happy to take a pull request that addresses concerns, correct?

**Comment by wifelette** [comment]
Mhmmm

**Pull request closed without merging**
