### PR TITLE
responsive blog with pagination

### PR DESCRIPTION
**Pull request by webofnithin**
Added pagination to blog pages and made it responsive ! please close this #2594 duplicate Pull request

### CODE REVIEW

**Comment by locks** [comment]
Can you post some screenshots/gifs so we can do a visual check, please?

**Comment by webofnithin** [comment]
Here are some screenshots 

image
image
image
image

**Comment by acorncom** [comment]
Looks good, thank you!

**Comment by webofnithin** [comment]
Blog authors will to have add "responsive: true" property to blog post pages to make them responsive

**Comment by mixonic** [comment]
@webofnithin could you possibly make a followup PR where the default is responsive and old problematic articles are flagged `responsive: false`? I worry we will not remember to put `responsive: true` in the header of every blog post. There are several authors and keeping them up to date on this kind of boilerplate is hard. I'd prefer a responsive default is possible.

**Pull request merged**
