### PR TITLE
Update Tailor Brands logo

### PR DESCRIPTION
**Pull request by nadavshatz**
We rebranded our site a few months ago.

This is the updated logo.

Thanks!

You can see the new logo live here https://www.tailorbrands.com

### CODE REVIEW

**Comment by locks** [comment]
Hi @nadavshatz, congrats on the stylish new logo :D
While you're up in the code, could you also add a `use` key to your [`users.yml` data](https://github.com/emberjs/website/blob/master/data/users.yml#L465-L467)? It's something we introduced after your original submission. You can see an example [further down in the document](https://github.com/emberjs/website/blob/master/data/users.yml#L745).

**Comment by locks** [comment]
@nadavshatz poke, could you address the `use` field so we can merge your contribution?

**Comment by nadavshatz** [comment]
@locks done! let me know if you'd like any more changes.

**Comment by nadavshatz** [comment]
Thanks for the merge @wifelette  :)

**Pull request merged**
